---
os: linux

dist: bionic

language: python

services: docker

cache:
- apt
- pip

jobs:
  include:
  - arch: arm64
    env: MOLECULE_DIST=raspbian MOLECULE_VERSION=buster

deploy:
  provider: script
  cleanup: false
  script:
  - make push
  on:
    branch: master

before_install:
- export IMAGE=${DOCKER_USERNAME}/molecule-${DIST}:${VERSION}
# Upgrade Docker.
- sudo apt-get update

install:
- pip install molecule docker ansible-lint testinfra

before_script:
- make

script:
# Test building Dockerfile.
- make molecule-test
