---
os: linux

dist: bionic

language: python

services: docker

cache:
- apt
- pip

jobs:
  include:
  - DIST: raspbian
    VERSION: buster
    arch: arch64

deploy:
  provider: script
  cleanup: false
  script:
  - make push
  on:
    branch: master

before_install:
- export IMAGE=${DOCKER_USERNAME}/molecule-${DIST}:${VERSION}
# Upgrade Docker.
- sudo apt-get update
- sudo apt-get -y install docker-ce

install:
- pip install molecule docker ansible-lint testinfra

before_script:
- make

script:
# Test building Dockerfile.
- make molecule-test
