---
dist: bionic

services: docker

cache:
- apt

env:
  matrix:
  - DIST: centos
    VERSION: 8
  - DIST: centos
    VERSION: 7
  - DIST: ubuntu
    VERSION: 20.04
  - DIST: ubuntu
    VERSION: 18.04
  - DIST: ubuntu
    VERSION: 16.04
  - DIST: debian
    VERSION: 10
  - DIST: debian
    VERSION: 9

deploy:
  provider: script
  skip_cleanup: true
  script:
  - make push
  on:
    branch: master

before_install:
- export IMAGE=${DOCKER_USERNAME}/molecule-${DIST}:${VERSION}
# Upgrade Docker.
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
- pip install molecule docker ansible testinfra

before_script:
- make

script:
# Test building Dockerfile.
- make test
