---
services: docker

cache:
- apt

env:
  matrix:
  - OS: ubuntu
    VERSION: 18.04
    TAG: latest

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
- export IMAGE=${DOCKER_USERNAME}/${OS}${VERSION}:${TAG}

# Test building Dockerfile.
- docker build -t ${IMAGE} . -f ${OS}.Dockerfile

# Test running the container.
- docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${IMAGE}

# Verify Ansible is available in the container.
- docker exec --tty test-container env TERM=xterm ansible --version
