---
os: linux

dist: bionic

arch:
- amd64
- arch32

language: python

services: docker

cache:
- apt
- pip

matrix:
  include:
  - DIST: raspbian
    VERSION: buster
deploy:
  provider: script
  cleanup: false
  script:
  - make push
  on:
    branch: master

before_install:
- export IMAGE=${DOCKER_USERNAME}/molecule-${DIST}:${VERSION}
# Upgrade Docker.
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
- pip install molecule docker ansible-lint testinfra

before_script:
- make

script:
# Test building Dockerfile.
- make molecule-test
