---
services: docker

cache:
- apt

env:
  matrix:
  - DIST: ubuntu
    VERSION: 16.04
    TAG: latest
  - DIST: ubuntu
    VERSION: 18.04
    TAG: latest

deploy:
  provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${IMAGE}
  on:
    branch: master

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
- export IMAGE=${DOCKER_USERNAME}/${DIST}${VERSION}:${TAG}
- export DOCKER_FILE=${dist}
# Test building Dockerfile.
- docker build --build-arg VERSION=${VERSION} -t ${IMAGE} . -f ${DIST}.Dockerfile

# Test running the container.
- docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${IMAGE}

# Verify Ansible is available in the container.
- docker exec --tty test-container env TERM=xterm ansible --version
